### ISSUE TITLE
compiler-rt submodule repo has moved

### ISSUE THREAD

**Issue by rwhitby** [lambdaconcept/lambdasoc-bios#2]
The url for compiler-rt in .gitmodules currently contains

http://llvm.org/git/compiler-rt

but this repository has moved to

https://github.com/llvm-mirror/compiler-rt

Commit 69445f0 is the head of the repository at the new location, so simply changing the url in .gitmodules should fix the issue.

**Comment by rwhitby** [comment]
Pull request submitted.

**Comment by megng1** [comment]
Closed by https://github.com/lambdaconcept/lambdasoc-bios/pull/1.
